#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the funnyString function below.
def funnyString(s):
    x=list()

    for i in range(0,len(s),1):
        
        
        x.append(ord(s[i]))
    
    y=list(s)
    y.reverse()
    z=list()
    
    for i in range(0,len(s),1):
        
        
        z.append(ord(y[i]))
    a=list()
    b=list()
    for i in range(0,len(s)-1,1):
        a.append(abs(x[i]-x[i+1]))
        b.append(abs(z[i]-z[i+1]))
 
    if(a==b):
        return "Funny"
    else:
        return "Not Funny"
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input())

    for q_itr in range(q):
        s = input()

        result = funnyString(s)

        fptr.write(result + '\n')

    fptr.close()
